const TITLE = "Dev-Utils Web"

const PORT = 3000

const ISSUE_STATUS_PENDING = "Pending"
const ISSUE_STATUS_IN_PROGRESS = "In Progress"
const ISSUE_STATUS_DONE = "Done"
const ISSUE_STATUS_CANCELLED = "Cancelled"

const ISSUE_STATUS_LIST = [ISSUE_STATUS_PENDING, ISSUE_STATUS_IN_PROGRESS, ISSUE_STATUS_DONE, ISSUE_STATUS_CANCELLED]

module.exports = {
    TITLE,
    PORT,
    ISSUE_STATUS_PENDING, ISSUE_STATUS_IN_PROGRESS, ISSUE_STATUS_DONE, ISSUE_STATUS_CANCELLED,
    ISSUE_STATUS_LIST
}