const TITLE = "Dev-Utils Web"

const PORT = 3000

const ISSUE_STATUS_TO_DO = "to_do"
const ISSUE_STATUS_IN_PROGRESS = "in_progress"
const ISSUE_STATUS_CLOSED = "closed"
const ISSUE_STATUS_CANCELLED = "cancelled"

const ISSUE_PROJECT_EAS = "EAS"
const ISSUE_PROJECT_FASTWEB = "FASTWEB"
const ISSUE_PROJECT_INTA_VP = "INT-A-VP"
const ISSUE_PROJECT_NFVD = "NFVD"
const ISSUE_PROJECT_NOT_DEFINED = "NOT_DEFINED"

const ISSUE_PROJECTS = [ISSUE_PROJECT_EAS, ISSUE_PROJECT_FASTWEB, ISSUE_PROJECT_INTA_VP, ISSUE_PROJECT_NFVD, ISSUE_PROJECT_NOT_DEFINED]

module.exports = {
    TITLE,
    PORT,
    ISSUE_STATUS_TO_DO, ISSUE_STATUS_IN_PROGRESS, ISSUE_STATUS_CLOSED, ISSUE_STATUS_CANCELLED,
    ISSUE_PROJECT_EAS, ISSUE_PROJECT_FASTWEB, ISSUE_PROJECT_INTA_VP, ISSUE_PROJECT_NFVD, ISSUE_PROJECT_NOT_DEFINED, 
    ISSUE_PROJECTS
}