const TITLE = "Dev-Utils Web"

const PORT = 3000

const ISSUE_STATUS_PENDING = "Pending"
const ISSUE_STATUS_IN_PROGRESS = "In Progress"
const ISSUE_STATUS_DONE = "Done"
const ISSUE_STATUS_CANCELLED = "Cancelled"

const ISSUE_STATUS_LIST = [ISSUE_STATUS_PENDING, ISSUE_STATUS_IN_PROGRESS, ISSUE_STATUS_DONE, ISSUE_STATUS_CANCELLED]

const ISSUE_PROJECT_EAS = "EAS"
const ISSUE_PROJECT_FASTWEB = "FASTWEB"
const ISSUE_PROJECT_INTA_VP = "INT-A-VP"
const ISSUE_PROJECT_NFVD = "NFVD"
const ISSUE_PROJECT_NOT_DEFINED = "NOT_DEFINED"

const ISSUE_PROJECTS = [ISSUE_PROJECT_EAS, ISSUE_PROJECT_FASTWEB, ISSUE_PROJECT_INTA_VP, ISSUE_PROJECT_NFVD, ISSUE_PROJECT_NOT_DEFINED]

module.exports = {
    TITLE,
    PORT,
    ISSUE_STATUS_PENDING, ISSUE_STATUS_IN_PROGRESS, ISSUE_STATUS_DONE, ISSUE_STATUS_CANCELLED,
    ISSUE_STATUS_LIST, 
    ISSUE_PROJECT_EAS, ISSUE_PROJECT_FASTWEB, ISSUE_PROJECT_INTA_VP, ISSUE_PROJECT_NFVD, ISSUE_PROJECT_NOT_DEFINED, 
    ISSUE_PROJECTS
}