services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - dev-utils

  dev-utils:
    build:
      context: .
    container_name: dev-utils
    ports:
      - "3000:3000"
    networks:
      - dev-utils

networks:
  dev-utils:
    driver: bridge

volumes:
  mongodb_data:
    external: true  
